### ISSUE TITLE
新建分类有几率出现多个分栏

### ISSUE THREAD

**Issue by KuiyueRO** [Morick66/obsidian-writer-suite#1]
每次出现的数量不一样，有时候三个有时候两个

![image](https://github.com/Morick66/obsidian-writer-suite/assets/63145205/66ecc2ab-971b-4578-8c62-52c8609bb7e1)

**Comment by Morick66** [comment]
是一个view刷新的bug，已经解决，等我发布下一个版本吧，还有新建书籍的时候也会出现书籍重复，也是一个刷新的bug。这两天解决了下一个版本发布

**Comment by KuiyueRO** [comment]
牛！

**Comment by Morick66** [comment]
版本0.2.0解决
